name: Sync Fork with Upstream

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Check if fork
        id: check_fork
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return repo.data.fork;

      - name: Checkout repository
        if: steps.check_fork.outputs.result == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEMPLATE_PAT }}
          fetch-depth: 0

      - name: Configure Git
        if: steps.check_fork.outputs.result == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Add upstream remote
        if: steps.check_fork.outputs.result == 'true'
        run: |
          git remote add upstream https://github.com/OrderlyNetworkDexCreator/dex-creator-template.git
          git fetch upstream

      - name: Sync branches
        if: steps.check_fork.outputs.result == 'true'
        run: |
          # Sync main branch
          git checkout main
          if git merge upstream/main --no-edit; then
            git push origin main
          else
            echo "Merge failed for main branch, skipping push"
          fi
